---
- name: Create /opt/poll directory
  file:
    path: /opt/poll
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Upload poll.tar archive
  copy:
    src: poll.tar
    dest: /tmp/poll.tar
    mode: '0644'

- name: Extract poll.tar into /opt/poll
  unarchive:
    src: /tmp/poll.tar
    dest: /opt/poll
    remote_src: yes

- name: Ensure python3-venv is installed
  apt:
    name: python3-venv
    state: present
  become: true

- name: Install Python dependencies for poll
  pip:
    requirements: /opt/poll/poll/requirements.txt
    virtualenv: /opt/poll/poll/venv
    virtualenv_command: python3 -m venv

- name: Template poll systemd service
  template:
    src: poll.service.j2
    dest: /etc/systemd/system/poll.service
    mode: '0644'
  notify: Restart poll service

- name: Enable and start poll service
  systemd:
    name: poll
    enabled: true
    state: started