name:                wolfram
version:             0.1.0.0
github:              "EpitechPromo2028/B-FUN-400-MPL-4-1-wolfram-vincent.bichat"
license:             BSD-3-Clause
author:              "Vincent Bichat"
maintainer:          "vincent.bichat@epitech.eu"
copyright:           "2025 Vincent Bichat"

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EpitechPromo2028/B-FUN-400-MPL-4-1-wolfram-vincent.bichat#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  wolfram:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wolfram
